<style>
    body, p, h1, h2, h3, li, span, div {
        font-family: 'Times New Roman', Times, serif !important;
    }
    ul ul, li li {
        list-style-type: none !important;
    }
    ul ul li::before, li li::before {
        content: "- " !important;
        display: inline-block;
        width: 1.2em;
        margin-left: -1.2em;
    }
    pre, code, .jp-OutputArea-output {
        font-family: Consolas, "Courier New", monospace !important;
    }
</style>

<br>

<div style="text-align: center;">
    <span style="font-size: 24px;">Programa2.Estandarización</span><br><br>
    <span>Septiembre 23, 2026</span><br><br><br>
    <img src="img/logoitqv1.jpg" width="450">
</div>

*Christian Villegas*

Link del repositorio: https://github.com/christian7villegas/Introducci-nPython

In [2]:
from sklearn import preprocessing
import numpy as np

In [3]:
# Carga de datos.
X_train = np.array([[ 1., -1., 2.],
                    [ 2., 0., 0.],
                    [ 0., 1., -1.]])

In [4]:
# Limpieza de datos: estandarización.
standardizer = preprocessing.StandardScaler()
# Estandarizamos los datos de entrenamiento
X_train_std=standardizer.fit_transform(X_train)
print(X_train_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [6]:
X_train_2 = np.array([[ 1., -1., 2.],
                      [ 2., 0., 0.],
                      [ 0., 1., -1.]])

In [7]:
# Aplicamos los métodos "fit" y "transform" por separado
f=preprocessing.StandardScaler()
f=f.fit(X_train)
X_train_2_std = f.transform(X_train_2)
print(X_train_2_std)
# ???

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [8]:
# Comprobar si las matrices estandarizadas son iguales
son_iguales = np.allclose(X_train_std, X_train_2_std)
print(son_iguales)

True
